/* زاد المسلم v4.8 — سلوك التطبيق، التنقل، المشغل المصغر والتشخيص. */
(function(){
  'use strict';
  const ERROR_KEY='zad_error_log';
  let restoring=false,lastAudio=null;
  const readErrors=()=>{try{return JSON.parse(localStorage.getItem(ERROR_KEY)||'[]')}catch(_){return[]}};
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function recordError(kind,error){const rows=readErrors(),message=String(error?.message||error||'خطأ غير معروف').slice(0,500),stack=String(error?.stack||'').slice(0,1800);rows.unshift({time:new Date().toISOString(),kind,message,stack,path:location.pathname,version:window.ZAD_APP?.version||''});localStorage.setItem(ERROR_KEY,JSON.stringify(rows.slice(0,50)))}
  window.addEventListener('error',event=>recordError('error',event.error||event.message));
  window.addEventListener('unhandledrejection',event=>recordError('promise',event.reason));

  function push(state){if(restoring)return;const current=history.state||{};if(JSON.stringify(current)===JSON.stringify(state))return;history.pushState(state,'',`#${state.view||state.tab||'home'}`)}
  const baseLoadTab=window.loadTab;
  window.loadTab=function(tab){baseLoadTab(tab);push({view:'tab',tab})};
  const baseOpenSurah=window.openSurah;
  window.openSurah=function(surah,ayah=1){baseOpenSurah(surah,ayah);push({view:'surah',surah:Number(surah),ayah:Number(ayah)||1})};
  const baseOpenAudio=window.openAudioReciter;
  window.openAudioReciter=async function(id){const result=await baseOpenAudio(id);push({view:'audio-reciter',id});return result};
  const baseDownloads=window.renderAudioDownloads;
  window.renderAudioDownloads=async function(){const result=await baseDownloads();push({view:'downloads'});return result};
  window.addEventListener('popstate',event=>{restoring=true;const state=event.state||{view:'tab',tab:'home'};try{if(state.view==='surah')baseOpenSurah(state.surah,state.ayah);else if(state.view==='audio-reciter')baseOpenAudio(state.id);else if(state.view==='downloads')baseDownloads();else if(state.view==='diagnostics')diagnostics();else baseLoadTab(state.tab||'home')}finally{setTimeout(()=>{restoring=false},0)}});
  window.addEventListener('load',()=>{const hash=location.hash.slice(1),tabs=['home','adhkar','tasbeeh','quran','audio-quran','themes','settings'],initial=tabs.includes(hash)?hash:'home';if(!history.state)history.replaceState({view:'tab',tab:initial},'',`#${initial}`);if(initial!=='home')setTimeout(()=>{restoring=true;baseLoadTab(initial);restoring=false},0);document.querySelectorAll('.nav-item').forEach(item=>{item.setAttribute('role','button');item.setAttribute('tabindex','0');item.setAttribute('aria-label',item.textContent.trim());item.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();window.loadTab(item.dataset.tab)}})})});

  function ensureMiniPlayer(){let bar=document.getElementById('zad-mini-player');if(bar)return bar;bar=document.createElement('section');bar.id='zad-mini-player';bar.className='zad-mini-player';bar.hidden=true;bar.innerHTML=`<button class="mini-close" onclick="closeMiniPlayer()" aria-label="إغلاق المشغل"><i class="fas fa-xmark"></i></button><div class="mini-info"><strong id="mini-title">القرآن الكريم</strong><small id="mini-subtitle"></small><div class="mini-progress"><span id="mini-progress-fill"></span></div></div><div class="mini-controls"><button onclick="miniPrevious()" aria-label="السابق"><i class="fas fa-backward-step"></i></button><button class="mini-main" onclick="miniToggle()" aria-label="تشغيل أو إيقاف"><i id="mini-play-icon" class="fas fa-play"></i></button><button onclick="miniNext()" aria-label="التالي"><i class="fas fa-forward-step"></i></button></div>`;document.body.appendChild(bar);return bar}
  window.addEventListener('zad:audio-state',event=>{lastAudio=event.detail;const bar=ensureMiniPlayer();bar.hidden=false;document.getElementById('mini-title').textContent=lastAudio.title;document.getElementById('mini-subtitle').textContent=lastAudio.subtitle;document.getElementById('mini-play-icon').className=`fas fa-${lastAudio.playing?'pause':'play'}`;const percent=lastAudio.duration?Math.min(100,lastAudio.currentTime/lastAudio.duration*100):0;document.getElementById('mini-progress-fill').style.width=`${percent}%`;document.body.classList.add('has-mini-player')});
  window.miniToggle=()=>lastAudio?.kind==='full'?window.toggleSurahAudio?.():window.toggleQuranAudio?.();
  window.miniPrevious=()=>lastAudio?.kind==='full'?window.surahAudioPrevious?.():window.quranAudioPrevious?.();
  window.miniNext=()=>lastAudio?.kind==='full'?window.surahAudioNext?.():window.quranAudioNext?.();
  window.closeMiniPlayer=()=>{if(lastAudio?.kind==='full')window.stopSurahAudio?.();else window.stopQuranAyahAudio?.();const bar=document.getElementById('zad-mini-player');if(bar)bar.hidden=true;document.body.classList.remove('has-mini-player');lastAudio=null};

  async function diagnostics(){const content=document.getElementById('page-content'),errors=readErrors(),storage=navigator.storage?.estimate?await navigator.storage.estimate():{},registration='serviceWorker'in navigator?await navigator.serviceWorker.getRegistration().catch(()=>null):null;content.className='fade-in diagnostics-page';content.innerHTML=`<div class="reader-toolbar"><button onclick="loadTab('settings')"><i class="fas fa-arrow-right"></i><span>الإعدادات</span></button><div><strong>فحص التطبيق</strong><small>بيانات محلية للمساعدة في اكتشاف الأعطال</small></div><span></span></div><div class="diagnostic-grid"><div><strong>${navigator.onLine?'متصل':'دون اتصال'}</strong><small>حالة الشبكة</small></div><div><strong>${registration?'يعمل':'غير مسجل'}</strong><small>Service Worker</small></div><div><strong>${window.matchMedia('(display-mode: standalone)').matches?'مثبت':'داخل المتصفح'}</strong><small>وضع التشغيل</small></div><div><strong>${formatBytes(storage.usage||0)}</strong><small>مساحة التطبيق</small></div></div><div class="card"><div class="card-title"><i class="fas fa-bug"></i> سجل الأخطاء المحلي</div><p class="accuracy-note">لا يُرسل السجل إلى أي خادم. يمكنك نسخه عند طلب الدعم.</p><div class="error-log">${errors.map(row=>`<article><strong>${esc(row.message)}</strong><small>${esc(new Date(row.time).toLocaleString('ar'))} • ${esc(row.kind)}</small></article>`).join('')||'<p>لم تُسجل أخطاء.</p>'}</div><div class="diagnostic-actions"><button class="app-button" onclick="exportAppDiagnostics()"><i class="fas fa-file-export"></i> تصدير السجل</button><button class="app-button danger" onclick="clearAppDiagnostics()"><i class="fas fa-trash"></i> مسح السجل</button></div></div><div class="card"><div class="card-title"><i class="fas fa-mobile-screen"></i> معلومات البيئة</div><p>الإصدار: ${esc(window.ZAD_APP?.version)}</p><p>المنصة: ${esc(navigator.platform||'غير معروفة')}</p><p class="diagnostic-agent">${esc(navigator.userAgent)}</p></div>`;push({view:'diagnostics'})}
  function formatBytes(value){if(value<1048576)return`${Math.round(value/1024)} ك.ب`;return`${(value/1048576).toFixed(1)} م.ب`}
  window.renderAppDiagnostics=diagnostics;
  window.exportAppDiagnostics=()=>{const blob=new Blob([JSON.stringify({app:'زاد المسلم',version:window.ZAD_APP?.version,exportedAt:new Date().toISOString(),errors:readErrors()},null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`zad-diagnostics-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)};
  window.clearAppDiagnostics=()=>{if(confirm('مسح سجل الأخطاء المحلي؟')){localStorage.removeItem(ERROR_KEY);diagnostics()}};
  const baseSettings=window.renderSettings;window.renderSettings=function(){baseSettings();document.getElementById('page-content')?.insertAdjacentHTML('beforeend',`<h3 class="settings-group-title">الفحص والدعم</h3><div class="card settings-card"><div class="card-title"><i class="fas fa-stethoscope"></i> تشخيص التطبيق</div><p class="settings-description">افحص الاتصال والتخزين وسجل الأخطاء قبل الإبلاغ عن مشكلة.</p><button class="app-button wide" onclick="renderAppDiagnostics()"><i class="fas fa-bug"></i> فتح صفحة التشخيص</button></div>`)};
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&'serviceWorker'in navigator)navigator.serviceWorker.getRegistration().then(reg=>reg?.update()).catch(()=>{})});
})();
