/* زاد المسلم v4.9 beta — جسر Capacitor للتنقل والإشعارات والملفات والروابط. */
(function(){
  'use strict';
  const native=()=>Boolean(window.Capacitor?.isNativePlatform?.()),plugin=name=>window.Capacitor?.Plugins?.[name];
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch(_){return fallback}};
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let lastBack=0;
  function route(url){try{const parsed=new URL(url),hash=parsed.hash.slice(1),tab=parsed.searchParams.get('tab')||hash;if(parsed.searchParams.has('surah')){window.openSurah?.(Number(parsed.searchParams.get('surah')),Number(parsed.searchParams.get('ayah'))||1);return}if(['home','adhkar','tasbeeh','quran','audio-quran','settings'].includes(tab))window.loadTab?.(tab)}catch(_){}}
  async function init(){if(!native())return;document.body.classList.add('native-app');const App=plugin('App'),StatusBar=plugin('StatusBar'),SplashScreen=plugin('SplashScreen'),Notifications=plugin('LocalNotifications');try{await StatusBar?.setBackgroundColor?.({color:'#063b28'});await StatusBar?.setStyle?.({style:'DARK'})}catch(_){}try{await SplashScreen?.hide?.()}catch(_){}App?.addListener?.('backButton',({canGoBack})=>{if(document.querySelector('.quran-video-dialog:not([hidden]),.ayah-mark-dialog:not([hidden])')){document.querySelector('.quran-video-dialog:not([hidden])')&&window.closeQuranVideoMaker?.();document.querySelector('.ayah-mark-dialog:not([hidden])')&&window.closeAyahMark?.();return}if(canGoBack||history.length>1){history.back();return}const now=Date.now();if(now-lastBack<1800)App.exitApp();else{lastBack=now;toast('اضغط رجوع مرة أخرى للخروج')}});App?.addListener?.('appUrlOpen',event=>route(event.url));Notifications?.addListener?.('localNotificationActionPerformed',event=>{const tab=event.notification?.extra?.route;if(tab)window.loadTab?.(tab)});await rescheduleIfAllowed()}
  function toast(text){let node=document.getElementById('native-toast');if(!node){node=document.createElement('div');node.id='native-toast';node.className='quran-toast';document.body.appendChild(node)}node.textContent=text;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),1800)}
  async function notificationPermission(request=false){const Notifications=plugin('LocalNotifications');if(!Notifications)return'denied';let status=await Notifications.checkPermissions();if(request&&status.display!=='granted')status=await Notifications.requestPermissions();return status.display}
  async function requestPermissions(){if(!native())return alert('هذه الصلاحيات متاحة داخل تطبيق Android فقط.');const notification=await notificationPermission(true);renderNativePermissions();toast(notification==='granted'?'تم منح إذن الإشعارات':'لم يُمنح إذن الإشعارات')}
  async function requestLocation(){if(!native())return alert('إذن الموقع الأصلي متاح داخل التطبيق فقط.');navigator.geolocation.getCurrentPosition(()=>{toast('تم منح إذن الموقع');renderNativePermissions()},()=>toast('لم يُمنح إذن الموقع'),{enableHighAccuracy:true,timeout:12000})}
  async function scheduleReminders(){const Notifications=plugin('LocalNotifications');if(!Notifications||await notificationPermission(true)!=='granted')return toast('يلزم السماح بالإشعارات');const notifications=[{id:101,title:'أذكار الصباح',body:'ابدأ يومك بذكر الله',schedule:{on:{hour:7,minute:0},repeats:true,allowWhileIdle:true},extra:{route:'adhkar'}},{id:102,title:'أذكار المساء',body:'حان وقت أذكار المساء',schedule:{on:{hour:18,minute:0},repeats:true,allowWhileIdle:true},extra:{route:'adhkar'}},{id:103,title:'ورد القرآن',body:'لا تنسَ وردك اليومي من القرآن الكريم',schedule:{on:{hour:20,minute:0},repeats:true,allowWhileIdle:true},extra:{route:'quran'}}];await Notifications.cancel({notifications:notifications.map(({id})=>({id}))}).catch(()=>{});await Notifications.schedule({notifications});await schedulePrayerNotifications();localStorage.setItem('zad_native_reminders','true');toast('تم تفعيل تذكيرات الأذكار والورد والصلاة')}
  async function schedulePrayerNotifications(){const Notifications=plugin('LocalNotifications'),cache=read('zad_prayer_v42_cache',null),settings=read('zad_prayer_alert_settings',{minutes:10});if(!Notifications||!cache?.times)return false;const names=[['الفجر','fajr'],['الظهر','dhuhr'],['العصر','asr'],['المغرب','maghrib'],['العشاء','isha']],now=new Date(),minutes=Math.max(0,Math.min(60,Number(settings.minutes)||10)),notifications=[];names.forEach(([name,key],index)=>{const match=String(cache.times[key]||'').match(/(\d{1,2}):(\d{2})/);if(!match)return;const at=new Date();at.setHours(Number(match[1]),Number(match[2])-minutes,0,0);if(at>now)notifications.push({id:200+index,title:`اقتربت صلاة ${name}`,body:`باقي ${minutes} دقيقة على الصلاة`,schedule:{at,allowWhileIdle:true},extra:{route:'home'}})});await Notifications.cancel({notifications:names.map((_,index)=>({id:200+index}))}).catch(()=>{});if(notifications.length)await Notifications.schedule({notifications});return true}
  async function disableReminders(){const Notifications=plugin('LocalNotifications');if(!Notifications)return;await Notifications.cancel({notifications:[101,102,103,200,201,202,203,204].map(id=>({id}))});localStorage.removeItem('zad_native_reminders');toast('تم إيقاف تذكيرات التطبيق');renderNativePermissions()}
  async function rescheduleIfAllowed(){if(localStorage.getItem('zad_native_reminders')==='true'&&await notificationPermission(false)==='granted')await schedulePrayerNotifications().catch(()=>{})}
  async function renderNativePermissions(){const content=document.getElementById('page-content');if(!content)return;const permission=native()?await notificationPermission(false):'web';content.className='fade-in native-permissions-page';content.innerHTML=`<div class="reader-toolbar"><button onclick="loadTab('settings')"><i class="fas fa-arrow-right"></i><span>الإعدادات</span></button><div><strong>الصلاحيات والتنبيهات</strong><small>${native()?'تطبيق Android':'نسخة الويب'}</small></div><span></span></div><div class="card permission-list"><article><i class="fas fa-bell"></i><div><strong>الإشعارات</strong><small>${esc(permission==='granted'?'مسموح':permission==='web'?'متاحة بعد تثبيت التطبيق':'غير مسموح')}</small></div><button class="app-button" onclick="requestNativePermissions()">طلب الإذن</button></article><article><i class="fas fa-location-dot"></i><div><strong>الموقع</strong><small>يُطلب فقط عند تحديد المواقيت والقبلة</small></div><button class="app-button" onclick="requestNativeLocation()">طلب الإذن</button></article><article><i class="fas fa-folder-open"></i><div><strong>الملفات</strong><small>تستخدم مساحة التطبيق الخاصة للتنزيل والتصدير</small></div><span>دون إذن عام</span></article></div><div class="card"><div class="card-title"><i class="fas fa-clock"></i> التذكيرات الأصلية</div><p>أذكار الصباح 7:00، المساء 18:00، الورد 20:00، وتنبيهات الصلاة من آخر مواقيت موثوقة.</p><div class="settings-actions"><button class="app-button" onclick="enableNativeReminders()"><i class="fas fa-bell"></i> تفعيل التذكيرات</button><button class="app-button danger" onclick="disableNativeReminders()"><i class="fas fa-bell-slash"></i> إيقافها</button></div></div><a class="app-button wide" href="privacy.html"><i class="fas fa-shield-halved"></i> سياسة الخصوصية</a>`}
  async function shareBlob(blob,name){if(!native())return false;const Filesystem=plugin('Filesystem'),Share=plugin('Share');if(!Filesystem||!Share)return false;const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(blob)}),saved=await Filesystem.writeFile({path:`exports/${name}`,data,directory:'CACHE',recursive:true});await Share.share({title:'زاد المسلم',files:[saved.uri],dialogTitle:'مشاركة المقطع'});return true}
  const baseSettings=window.renderSettings;window.renderSettings=function(){baseSettings();document.getElementById('page-content')?.insertAdjacentHTML('beforeend',`<h3 class="settings-group-title">تطبيق Android</h3><div class="card settings-card"><div class="card-title"><i class="fas fa-mobile-screen"></i> الصلاحيات والتنبيهات</div><p class="settings-description">تحكم في إشعارات الصلاة والأذكار والورد والصلاحيات من صفحة واحدة.</p><button class="app-button wide" onclick="renderNativePermissions()"><i class="fas fa-shield-halved"></i> فتح صفحة الصلاحيات</button></div>`)};
  window.renderNativePermissions=renderNativePermissions;window.requestNativePermissions=requestPermissions;window.requestNativeLocation=requestLocation;window.enableNativeReminders=scheduleReminders;window.disableNativeReminders=disableReminders;window.nativeShareBlob=shareBlob;
  window.addEventListener('load',init);
})();
