/* زاد المسلم v4.9.3-beta.2 — فيديو قرآن بلا إطار خارجي، MP4 إن دعمه المتصفح وإلا WebM. */
(function(){
  'use strict';
  const ROOT='https://everyayah.com/data/',SOURCE='EveryAyah.com',MAX_SECONDS=60;
  let context=null,dialog=null,recording=false,cancelled=false,resultUrl='';
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pad=value=>String(value).padStart(3,'0');
  const reciterId=()=>document.getElementById('audio-reciter')?.value||JSON.parse(localStorage.getItem('zad_audio_settings')||'{}').reciter||'Alafasy_64kbps';
  const reciterName=()=>document.getElementById('audio-reciter')?.selectedOptions?.[0]?.textContent?.replace(/\s+—\s+(حفص|ورش).*$/,'')||reciterId();
  const audioUrl=(surah,ayah,id)=>`${ROOT}${String(id).split('/').map(encodeURIComponent).join('/')}/${pad(surah)}${pad(ayah)}.mp3`;
  function inject(payload){context=payload;const range=document.querySelector('.audio-range');if(!range||document.getElementById('quran-video-open'))return;range.insertAdjacentHTML('afterend','<button id="quran-video-open" class="app-button quran-video-open" onclick="openQuranVideoMaker()"><i class="fas fa-video"></i> مشاركة مقطع قرآني</button>')}
  function ensureDialog(){
    if(dialog)return dialog;
    dialog=document.createElement('div');dialog.className='quran-video-dialog';dialog.hidden=true;
    dialog.innerHTML=`<section class="quran-video-sheet" role="dialog" aria-modal="true" aria-labelledby="quran-video-title"><button class="dialog-close" onclick="closeQuranVideoMaker()" aria-label="إغلاق"><i class="fas fa-xmark"></i></button><h3 id="quran-video-title"><i class="fas fa-video"></i> إنشاء مقطع قرآن</h3><p class="accuracy-note">الفيديو نفسه بلا إطار تطبيق أو أزرار. الحد الافتراضي ${MAX_SECONDS} ثانية، ويُستخدم MP4 عند دعم المتصفح وإلا WebM.</p><div class="quran-video-fields"><label>من الآية<input id="video-start" type="number" min="1"></label><label>إلى الآية<input id="video-end" type="number" min="1"></label><label>الخلفية<select id="video-background" onchange="previewQuranVideo()"><option value="black">سوداء</option><option value="green">خضراء داكنة</option><option value="navy">كحلية داكنة</option></select></label><label>المقاس<select id="video-size" onchange="previewQuranVideo()"><option value="story">عمودي — 1080×1920</option><option value="square">مربع — 1080×1080</option><option value="landscape">أفقي — 1920×1080</option></select></label><label>جودة التصدير<select id="video-quality"><option value="compatible">متوافقة</option><option value="high">عالية</option><option value="small">حجم أصغر</option></select></label></div><canvas id="quran-video-canvas" width="540" height="960" aria-label="معاينة المقطع"></canvas><div id="video-progress" class="video-render-progress" hidden><span></span><small>جاري تجهيز الصوت…</small></div><div class="quran-video-actions"><button id="video-create" class="app-button" onclick="createQuranVideo()"><i class="fas fa-film"></i> إنشاء الفيديو</button><button id="video-image" class="app-button" onclick="saveQuranVideoFrame()"><i class="fas fa-image"></i> حفظ صورة</button><button id="video-cancel" class="app-button danger" onclick="cancelQuranVideo()" hidden><i class="fas fa-stop"></i> إلغاء</button></div><div id="video-result" class="quran-video-result"></div><small class="video-compatibility">في Android استخدم المشاركة الأصلية. في الويب: MP4 إذا دعمه المتصفح، وإلا WebM مع تنبيه واضح.</small></section>`;
    dialog.addEventListener('click',event=>{if(event.target===dialog&&!recording)close()});document.body.appendChild(dialog);return dialog;
  }
  function open(){if(!context)return alert('افتح سورة أولًا.');ensureDialog();const max=context.verses.length,start=Math.max(1,Number(document.getElementById('audio-range-start')?.value)||context.ayahNumber||1),end=Math.min(max,Number(document.getElementById('audio-range-end')?.value)||start);for(const [id,value] of [['video-start',start],['video-end',Math.min(end,start+2)]]){const input=document.getElementById(id);input.max=max;input.value=value;input.oninput=preview}dialog.hidden=false;document.body.classList.add('dialog-open');preview()}
  function close(){if(recording)return;dialog.hidden=true;document.body.classList.remove('dialog-open')}
  function selection(){const start=Math.max(1,Number(document.getElementById('video-start').value)||1),end=Math.min(context.verses.length,Number(document.getElementById('video-end').value)||start);if(end<start)throw Error('رقم آية النهاية يجب أن يكون بعد البداية.');if(end-start+1>10)throw Error('الحد الحالي عشر آيات للمقطع الواحد.');return{start,end}}
  function colors(kind){if(kind==='green')return['#061f16','#0d5137','#d9b85b'];if(kind==='navy')return['#050b1c','#122d59','#d7bd72'];return['#000','#111','#d7bd72']}
  function wrap(ctx,text,width){const words=text.split(/\s+/),lines=[];let line='';for(const word of words){const test=`${line} ${word}`.trim();if(ctx.measureText(test).width>width&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);return lines}
  function draw(ayah,progress=0){
    const canvas=document.getElementById('quran-video-canvas'),size=document.getElementById('video-size')?.value||'story';canvas.width=size==='square'?540:size==='landscape'?960:540;canvas.height=size==='square'?540:size==='landscape'?540:960;
    const ctx=canvas.getContext('2d'),[top,bottom,gold]=colors(document.getElementById('video-background')?.value);const gradient=ctx.createLinearGradient(0,0,canvas.width,canvas.height);gradient.addColorStop(0,top);gradient.addColorStop(1,bottom);ctx.fillStyle=gradient;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.direction='rtl';ctx.textAlign='center';
    ctx.fillStyle=gold;ctx.font='700 22px Tajawal, sans-serif';ctx.fillText(`سورة ${context.chapter.name}`,canvas.width/2,64);const verse=context.verses[ayah-1],label=`${verse?.text||''} ﴿${ayah}﴾`;ctx.fillStyle='#fff';ctx.font=`${size==='square'?'27px':size==='landscape'?'30px':'30px'} Amiri, serif`;const lines=wrap(ctx,label,canvas.width-96),lineHeight=size==='square'?47:54,center=canvas.height/2-lines.length*lineHeight/2+10;lines.forEach((line,index)=>ctx.fillText(line,canvas.width/2,center+index*lineHeight));ctx.fillStyle='rgba(255,255,255,.86)';ctx.font='600 16px Tajawal, sans-serif';ctx.fillText(`الآية ${ayah} • ${reciterName()}`,canvas.width/2,canvas.height-62);
  }
  function preview(){if(!context)return;try{const{start}=selection();draw(start,0)}catch(_){draw(1,0)}}
  async function fetchBuffers(audioContext,start,end,id){const rows=[];for(let ayah=start;ayah<=end;ayah++){status(`تحميل الآية ${ayah}…`,(ayah-start)/(end-start+1)*30);const response=await fetch(audioUrl(context.surahId,ayah,id));if(!response.ok)throw Error(`تعذر تحميل صوت الآية ${ayah}`);const buffer=await audioContext.decodeAudioData(await response.arrayBuffer());rows.push({ayah,buffer});if(cancelled)throw Error('cancelled')}return rows}
  function recorderOptions(){const quality=document.getElementById('video-quality')?.value||'compatible',types=['video/mp4;codecs=avc1.42E01E,mp4a.40.2','video/mp4','video/webm;codecs=vp8,opus','video/webm;codecs=vp9,opus','video/webm'];const mimeType=types.find(type=>MediaRecorder.isTypeSupported(type))||'';return{mimeType,extension:mimeType.startsWith('video/mp4')?'mp4':'webm',videoBitsPerSecond:quality==='high'?3500000:quality==='small'?1200000:2200000}}
  async function create(){
    if(recording)return;if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream)return fail('هذا المتصفح لا يدعم إنشاء الفيديو. استخدم «حفظ صورة» أو جرّب Chrome حديثًا.');let range;try{range=selection()}catch(error){return fail(error.message)}recording=true;cancelled=false;toggleBusy(true);window.stopQuranAyahAudio?.();window.stopSurahAudio?.();let audioContext;
    try{await document.fonts?.ready;audioContext=new(window.AudioContext||window.webkitAudioContext)();await audioContext.resume();const rows=await fetchBuffers(audioContext,range.start,range.end,reciterId()),duration=rows.reduce((sum,row)=>sum+row.buffer.duration,0);if(duration>MAX_SECONDS)throw Error(`مدة المقطع ${Math.ceil(duration)} ثانية وتتجاوز الحد ${MAX_SECONDS} ثانية. اختر آيات أقل.`);const canvas=document.getElementById('quran-video-canvas'),videoStream=canvas.captureStream(24),destination=audioContext.createMediaStreamDestination(),stream=new MediaStream([...videoStream.getVideoTracks(),...destination.stream.getAudioTracks()]),options=recorderOptions(),chunks=[],recorder=new MediaRecorder(stream,options.mimeType?options:undefined);recorder.ondataavailable=event=>{if(event.data.size)chunks.push(event.data)};const stopped=new Promise((resolve,reject)=>{recorder.onstop=resolve;recorder.onerror=()=>reject(Error('تعذر ترميز الفيديو'))});recorder.start(1000);let elapsed=0;for(const row of rows){if(cancelled)break;const source=audioContext.createBufferSource();source.buffer=row.buffer;source.connect(destination);const started=audioContext.currentTime,timer=setInterval(()=>{const local=Math.min(row.buffer.duration,audioContext.currentTime-started);draw(row.ayah,(elapsed+local)/duration);status(`إنشاء الفيديو — الآية ${row.ayah}…`,30+(elapsed+local)/duration*65)},100);source.start();await new Promise(resolve=>{source.onended=resolve});clearInterval(timer);elapsed+=row.buffer.duration}recorder.stop();await stopped;videoStream.getTracks().forEach(track=>track.stop());if(cancelled){fail('تم إلغاء إنشاء المقطع.');return}const blob=new Blob(chunks,{type:options.mimeType||'video/webm'});showResult(blob,range,options.extension);status(`اكتمل إنشاء ${options.extension.toUpperCase()}.`,100)}catch(error){if(error.message!=='cancelled')fail(error.message.includes('Failed to fetch')?'تعذر جلب التلاوة. تحقق من الاتصال أو قيود المصدر.':error.message);else fail('تم إلغاء إنشاء المقطع.')}finally{recording=false;toggleBusy(false);audioContext?.close().catch(()=>{})}
  }
  function status(message,percent){const box=document.getElementById('video-progress');if(!box)return;box.hidden=false;box.querySelector('small').textContent=message;box.querySelector('span').style.width=`${percent}%`}
  function fail(message){const result=document.getElementById('video-result');if(!result)return;result.querySelector('.video-share-error')?.remove();result.insertAdjacentHTML('afterbegin',`<p class="error video-share-error"><i class="fas fa-triangle-exclamation"></i> ${esc(message)}</p>`)}
  function toggleBusy(busy){document.getElementById('video-create').disabled=busy;document.getElementById('video-image').disabled=busy;document.getElementById('video-cancel').hidden=!busy}
  function showResult(blob,range,extension){if(resultUrl)URL.revokeObjectURL(resultUrl);resultUrl=URL.createObjectURL(blob);const result=document.getElementById('video-result'),name=`zad-quran-${context.surahId}-${range.start}-${range.end}.${extension}`;result.innerHTML=`<video src="${resultUrl}" controls playsinline></video><div class="video-share-grid"><a class="app-button" href="${resultUrl}" download="${name}"><i class="fas fa-download"></i> حفظ ${extension.toUpperCase()}</a><button class="app-button" onclick="shareCreatedQuranVideo('${name}')"><i class="fas fa-share-nodes"></i> مشاركة ${extension.toUpperCase()}</button><button class="app-button" onclick="shareQuranVideoImage()"><i class="fas fa-image"></i> مشاركة صورة</button><button class="app-button" onclick="copyQuranVideoText()"><i class="fas fa-copy"></i> نسخ نص الآيات</button></div><p class="video-share-note">${extension==='mp4'?'ملف MP4 متوافق مع تطبيقات المشاركة.':'المتصفح لم يدعم MP4؛ تم إنشاء WebM ويمكن حفظه أو مشاركة الصورة.'}</p>`;result.dataset.name=name;result.dataset.start=range.start;result.dataset.end=range.end;result._blob=blob}
  async function share(name){const result=document.getElementById('video-result'),blob=result?._blob;if(!blob)return;if(window.nativeShareBlob){try{if(await window.nativeShareBlob(blob,name))return}catch(_){} }const file=new File([blob],name,{type:blob.type});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:'زاد المسلم'});return}catch(error){if(error.name==='AbortError')return}}fail('تعذرت المشاركة المباشرة؛ استخدم حفظ الملف ثم شاركه من مدير الملفات.')}
  function selectedText(){const result=document.getElementById('video-result'),range=result?.dataset.start?{start:Number(result.dataset.start),end:Number(result.dataset.end)}:selection(),verses=[];for(let ayah=range.start;ayah<=range.end;ayah++)verses.push(`${context.verses[ayah-1]?.text||''} ﴿${ayah}﴾`);return`${verses.join('\n')}\nسورة ${context.chapter.name}\nتلاوة: ${reciterName()} — المصدر: ${SOURCE}`}
  async function shareImage(){const result=document.getElementById('video-result'),ayah=Number(result?.dataset.start)||selection().start;draw(ayah,0);const blob=await new Promise(resolve=>document.getElementById('quran-video-canvas').toBlob(resolve,'image/png'));if(!blob)return;const file=new File([blob],`zad-quran-${context.surahId}-${ayah}.png`,{type:'image/png'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],text:selectedText()});return}catch(error){if(error.name==='AbortError')return}}const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
  async function copyText(){const text=selectedText();try{await navigator.clipboard.writeText(text);alert('تم نسخ نص الآيات وبيانات القارئ.')}catch(_){const area=document.createElement('textarea');area.value=text;document.body.appendChild(area);area.select();document.execCommand('copy');area.remove();alert('تم نسخ النص.')}}
  function saveFrame(){try{const{start}=selection();draw(start,0);document.getElementById('quran-video-canvas').toBlob(blob=>{if(!blob)return;const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`zad-quran-${context.surahId}-${start}.png`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)},'image/png')}catch(error){fail(error.message)}}
  function cancel(){cancelled=true}
  const oldHook=window.onQuranSurahOpened;window.onQuranSurahOpened=async payload=>{await oldHook?.(payload);inject(payload)};
  window.openQuranVideoMaker=open;window.closeQuranVideoMaker=close;window.previewQuranVideo=preview;window.createQuranVideo=create;window.cancelQuranVideo=cancel;window.saveQuranVideoFrame=saveFrame;window.shareCreatedQuranVideo=share;window.shareQuranVideoImage=shareImage;window.copyQuranVideoText=copyText;
})();
