/* زاد المسلم v4.8 — وضع الحفظ، القوائم المحلية ومشاركة الآية كصورة. */
(function(){
  'use strict';
  const MODE='zad_memorization_mode',PLAYLISTS='zad_quran_playlists';
  let data=null,chapters=null,current=null;
  const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch(_){return fallback}};
  const write=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function load(){if(data)return;const[a,b]=await Promise.all([fetch('quran-data/uthmani.json'),fetch('quran-data/chapters.json')]);data=await a.json();chapters=(await b.json()).chapters}
  function decorate(payload){current=payload;const toolbar=document.querySelector('.reader-toolbar');if(toolbar&&!document.getElementById('memorization-toggle'))toolbar.insertAdjacentHTML('afterend',`<div class="memorization-tools"><button id="memorization-toggle" class="app-button" onclick="toggleMemorizationMode()"><i class="fas fa-eye-slash"></i> وضع الحفظ</button><button class="app-button" onclick="renderQuranPlaylists()"><i class="fas fa-list-ul"></i> قوائم الحفظ</button></div>`);document.getElementById('quran-verses')?.classList.toggle('memorization-hidden',read(MODE,false));payload.verses.forEach(verse=>{const actions=document.querySelector(`#ayah-${payload.surahId}-${verse.verse} .ayah-actions`);if(actions&&!actions.querySelector('.playlist-add'))actions.insertAdjacentHTML('beforeend',`<button class="playlist-add" onclick="event.stopPropagation();addAyahToPlaylist(${payload.surahId},${verse.verse})"><i class="fas fa-list-ul"></i><span>إلى قائمة</span></button><button onclick="event.stopPropagation();shareAyahImage(${payload.surahId},${verse.verse})"><i class="fas fa-image"></i><span>كصورة</span></button>`)})}
  function toggleMode(){const next=!read(MODE,false);write(MODE,next);document.getElementById('quran-verses')?.classList.toggle('memorization-hidden',next);document.getElementById('memorization-toggle')?.classList.toggle('active',next)}
  async function add(surah,ayah){await load();const lists=read(PLAYLISTS,[]),suggest=lists[0]?.name||'قائمة الحفظ',name=prompt('اسم القائمة',suggest)?.trim();if(!name)return;let list=lists.find(item=>item.name===name);if(!list){list={id:String(Date.now()),name,items:[],createdAt:Date.now()};lists.unshift(list)}if(!list.items.some(item=>item.surah===surah&&item.ayah===ayah))list.items.push({surah,ayah,addedAt:Date.now()});write(PLAYLISTS,lists);alert('تمت إضافة الآية إلى القائمة')}
  async function render(){await load();const lists=read(PLAYLISTS,[]),content=document.getElementById('page-content');content.innerHTML=`<div class="reader-toolbar"><button onclick="renderQuranHome()"><i class="fas fa-arrow-right"></i><span>القرآن</span></button><div><strong>قوائم الحفظ</strong><small>قوائم محلية خاصة بك</small></div><span></span></div><div class="playlist-list">${lists.map(list=>`<section class="card"><div class="card-title"><i class="fas fa-list-ul"></i> ${esc(list.name)} <small>${list.items.length} آية</small></div>${list.items.map(item=>`<article><button onclick="openSurah(${item.surah},${item.ayah})"><strong>سورة ${esc(chapters[item.surah-1]?.name)} — ${item.ayah}</strong><span>${esc(data[String(item.surah)]?.[item.ayah-1]?.text||'')}</span></button><button class="danger" onclick="removePlaylistAyah('${esc(list.id)}',${item.surah},${item.ayah})" aria-label="حذف"><i class="fas fa-trash"></i></button></article>`).join('')||'<p>القائمة فارغة.</p>'}</section>`).join('')||'<div class="quran-empty">أنشئ قائمة من زر «إلى قائمة» بجوار أي آية.</div>'}</div>`}
  function remove(id,surah,ayah){const lists=read(PLAYLISTS,[]),list=lists.find(item=>item.id===id);if(list)list.items=list.items.filter(item=>item.surah!==surah||item.ayah!==ayah);write(PLAYLISTS,lists.filter(item=>item.items.length));render()}
  function wrapText(ctx,text,maxWidth){const words=text.split(' '),lines=[];let line='';for(const word of words){const test=`${line} ${word}`.trim();if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);return lines}
  async function shareImage(surah,ayah){await load();const verse=data[String(surah)]?.[ayah-1];if(!verse)return;const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1080;const ctx=canvas.getContext('2d'),gradient=ctx.createLinearGradient(0,0,1080,1080);gradient.addColorStop(0,'#082d20');gradient.addColorStop(1,'#146b48');ctx.fillStyle=gradient;ctx.fillRect(0,0,1080,1080);ctx.strokeStyle='#d5b45b';ctx.lineWidth=5;ctx.strokeRect(55,55,970,970);ctx.direction='rtl';ctx.textAlign='center';ctx.fillStyle='#fff';ctx.font='52px Amiri, serif';const lines=wrapText(ctx,`${verse.text} ﴿${ayah}﴾`,850),height=70,start=Math.max(180,540-lines.length*height/2);lines.forEach((line,index)=>ctx.fillText(line,540,start+index*height));ctx.fillStyle='#d5b45b';ctx.font='bold 36px Tajawal, sans-serif';ctx.fillText(`سورة ${chapters[surah-1].name}`,540,900);ctx.fillStyle='rgba(255,255,255,.75)';ctx.font='25px Tajawal, sans-serif';ctx.fillText('زاد المسلم',540,965);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)return;const file=new File([blob],`ayah-${surah}-${ayah}.png`,{type:'image/png'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({title:'آية من القرآن الكريم',files:[file]});return}catch(error){if(error.name==='AbortError')return}}const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
  const oldHook=window.onQuranSurahOpened;window.onQuranSurahOpened=async payload=>{await oldHook?.(payload);decorate(payload)};
  window.toggleMemorizationMode=toggleMode;window.addAyahToPlaylist=add;window.renderQuranPlaylists=render;window.removePlaylistAyah=remove;window.shareAyahImage=shareImage;
})();
