/* زاد المسلم v4.7 — العلامات الملونة وملاحظات الآيات. */
(function(){
  'use strict';
  const KEY='zad_quran_bookmarks',COLORS={reading:['متابعة القراءة','#2e8b57'],memorize:['آيات الحفظ','#2f80ed'],reflect:['تدبر','#9b59b6'],review:['مراجعة','#d88916']};
  let quran=null,chapters=null,editing=null;
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch(_){return[]}};
  const write=value=>localStorage.setItem(KEY,JSON.stringify(value));
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function load(){if(quran&&chapters)return;const[a,b]=await Promise.all([fetch('quran-data/uthmani.json'),fetch('quran-data/chapters.json')]);if(!a.ok||!b.ok)throw Error('تعذر تحميل بيانات القرآن');quran=await a.json();chapters=(await b.json()).chapters}
  function mark(surah,ayah){return read().find(item=>Number(item.surah)===Number(surah)&&Number(item.ayah)===Number(ayah))}
  function decorate(payload){
    payload.verses.forEach(verse=>{const node=document.getElementById(`ayah-${payload.surahId}-${verse.verse}`);if(!node)return;const item=mark(payload.surahId,verse.verse);node.dataset.markType=item?.type||'';node.classList.toggle('has-note',Boolean(item?.note));const actions=node.querySelector('.ayah-actions');if(actions&&!actions.querySelector('.ayah-note-button'))actions.insertAdjacentHTML('beforeend',`<button class="ayah-note-button" onclick="event.stopPropagation();editAyahMark(${payload.surahId},${verse.verse})"><i class="${item?.note?'fas':'far'} fa-note-sticky"></i><span>${item?.note?'ملاحظة':'إضافة ملاحظة'}</span></button>`)});
  }
  function ensureDialog(){
    let dialog=document.getElementById('ayah-mark-dialog');if(dialog)return dialog;
    dialog=document.createElement('div');dialog.id='ayah-mark-dialog';dialog.className='ayah-mark-dialog';dialog.hidden=true;
    dialog.innerHTML=`<div class="ayah-mark-sheet" role="dialog" aria-modal="true"><button class="dialog-close" onclick="closeAyahMark()" aria-label="إغلاق"><i class="fas fa-xmark"></i></button><h3><i class="fas fa-bookmark"></i> علامة وملاحظة الآية</h3><label>التصنيف<select id="ayah-mark-type">${Object.entries(COLORS).map(([id,[name]])=>`<option value="${id}">${name}</option>`).join('')}</select></label><label>ملاحظة خاصة<textarea id="ayah-mark-note" maxlength="1000" rows="5" placeholder="اكتب تدبرًا أو فائدة أو سبب الحفظ…"></textarea></label><small>تحفظ الملاحظة محليًا على جهازك وتدخل في النسخة الاحتياطية.</small><div class="dialog-actions"><button class="app-button" onclick="saveAyahMark()"><i class="fas fa-floppy-disk"></i> حفظ</button><button id="delete-ayah-mark" class="app-button danger" onclick="deleteAyahMark()"><i class="fas fa-trash"></i> حذف</button></div></div>`;
    dialog.addEventListener('click',event=>{if(event.target===dialog)closeDialog()});document.body.appendChild(dialog);return dialog;
  }
  function edit(surah,ayah){editing={surah:Number(surah),ayah:Number(ayah)};const item=mark(surah,ayah),dialog=ensureDialog();document.getElementById('ayah-mark-type').value=item?.type||'reading';document.getElementById('ayah-mark-note').value=item?.note||'';document.getElementById('delete-ayah-mark').hidden=!item;dialog.hidden=false;document.getElementById('ayah-mark-note').focus()}
  function closeDialog(){const dialog=document.getElementById('ayah-mark-dialog');if(dialog)dialog.hidden=true;editing=null}
  function save(){if(!editing)return;const items=read(),index=items.findIndex(item=>item.surah===editing.surah&&item.ayah===editing.ayah),item={...editing,type:document.getElementById('ayah-mark-type').value,note:document.getElementById('ayah-mark-note').value.trim(),savedAt:index>=0?items[index].savedAt:Date.now(),updatedAt:Date.now()};if(index>=0)items[index]=item;else items.unshift(item);write(items);const saved={...editing};closeDialog();window.openSurah(saved.surah,saved.ayah)}
  function remove(){if(!editing||!confirm('حذف العلامة والملاحظة من هذه الآية؟'))return;const target={...editing};write(read().filter(item=>item.surah!==target.surah||item.ayah!==target.ayah));closeDialog();window.openSurah(target.surah,target.ayah)}
  async function show(filter='all',query=''){
    await load();const content=document.getElementById('page-content'),normalized=query.trim().toLowerCase();let items=read();items=items.filter(item=>(filter==='all'||item.type===filter)&&(!normalized||String(item.note||'').toLowerCase().includes(normalized)||chapters[item.surah-1]?.name.includes(normalized)||String(item.ayah)===normalized));
    content.innerHTML=`<div class="reader-toolbar"><button onclick="renderQuranHome()"><i class="fas fa-arrow-right"></i><span>القرآن</span></button><div><strong>العلامات والملاحظات</strong><small>${items.length} نتيجة</small></div><span></span></div><div class="mark-filters"><input id="mark-search" type="search" placeholder="ابحث في الملاحظات أو السور" value="${esc(query)}" oninput="filterQuranMarks(document.getElementById('mark-type').value,this.value)"><select id="mark-type" onchange="filterQuranMarks(this.value,document.getElementById('mark-search').value)"><option value="all">كل التصنيفات</option>${Object.entries(COLORS).map(([id,[name]])=>`<option value="${id}" ${filter===id?'selected':''}>${name}</option>`).join('')}</select></div><div class="bookmark-list">${items.map(item=>{const verse=quran[String(item.surah)]?.[item.ayah-1],meta=COLORS[item.type]||COLORS.reading;return verse?`<article class="bookmark-card rich-mark" style="--mark-color:${meta[1]}" onclick="openSurah(${item.surah},${item.ayah})"><strong>${meta[0]} • سورة ${esc(chapters[item.surah-1].name)} — الآية ${item.ayah}</strong><p>${esc(verse.text)}</p>${item.note?`<blockquote>${esc(item.note)}</blockquote>`:''}<button onclick="event.stopPropagation();editAyahMark(${item.surah},${item.ayah})"><i class="fas fa-pen"></i></button></article>`:''}).join('')||'<div class="quran-empty">لا توجد علامات مطابقة.</div>'}</div>`;
    if(query){const input=document.getElementById('mark-search');input?.focus();input?.setSelectionRange(query.length,query.length)}
  }
  const oldHook=window.onQuranSurahOpened;window.onQuranSurahOpened=async payload=>{await oldHook?.(payload);decorate(payload)};
  window.toggleAyahBookmark=(surah,ayah)=>edit(surah,ayah);window.editAyahMark=edit;window.saveAyahMark=save;window.deleteAyahMark=remove;window.closeAyahMark=closeDialog;window.showQuranBookmarks=()=>show();window.filterQuranMarks=show;
})();
