const CACHE_NAME = 'zad-al-muslim-v4-9-3-beta-5-2-ui3';
const AUDIO_CACHE = 'zad-quran-audio-v45';
const AZKAR_AUDIO_ASSETS = [
  './assets/audio/azkari/adkaralmsa_2.mp3',
  './assets/audio/azkari/agmadalmayt_part.mp3',
  './assets/audio/azkari/al7mdo_llah_part.mp3',
  './assets/audio/azkari/al_mulk.mp3',
  './assets/audio/azkari/al_nawm_1.mp3',
  './assets/audio/azkari/al_nawm_10.mp3',
  './assets/audio/azkari/al_nawm_11.mp3',
  './assets/audio/azkari/al_nawm_12_1.mp3',
  './assets/audio/azkari/al_nawm_12_2.mp3',
  './assets/audio/azkari/al_nawm_14.mp3',
  './assets/audio/azkari/al_nawm_2.mp3',
  './assets/audio/azkari/al_nawm_3.mp3',
  './assets/audio/azkari/al_nawm_4.mp3',
  './assets/audio/azkari/al_nawm_5.mp3',
  './assets/audio/azkari/al_nawm_6.mp3',
  './assets/audio/azkari/al_nawm_7.mp3',
  './assets/audio/azkari/al_nawm_8.mp3',
  './assets/audio/azkari/al_nawm_9.mp3',
  './assets/audio/azkari/al_sajda.mp3',
  './assets/audio/azkari/alaado_part.mp3',
  './assets/audio/azkari/alestska_part1.mp3',
  './assets/audio/azkari/alestska_part2.mp3',
  './assets/audio/azkari/alestska_part3.mp3',
  './assets/audio/azkari/allah_eny_asalok.mp3',
  './assets/audio/azkari/allahom_saly.mp3',
  './assets/audio/azkari/alm3wzat_part.mp3',
  './assets/audio/azkari/almreed_part1.mp3',
  './assets/audio/azkari/almreed_part2.mp3',
  './assets/audio/azkari/almreed_part3.mp3',
  './assets/audio/azkari/altazyeh_part1.mp3',
  './assets/audio/azkari/altazyeh_part2.mp3',
  './assets/audio/azkari/astagfer_allah.mp3',
  './assets/audio/azkari/dfn_almayt_part.mp3',
  './assets/audio/azkari/dkhol_almayt_alhbr_part.mp3',
  './assets/audio/azkari/dkholalqrya_part.mp3',
  './assets/audio/azkari/esteghfar_1.mp3',
  './assets/audio/azkari/esteghfar_10.mp3',
  './assets/audio/azkari/esteghfar_2.mp3',
  './assets/audio/azkari/esteghfar_3.mp3',
  './assets/audio/azkari/esteghfar_4.mp3',
  './assets/audio/azkari/esteghfar_5.mp3',
  './assets/audio/azkari/esteghfar_6.mp3',
  './assets/audio/azkari/esteghfar_7.mp3',
  './assets/audio/azkari/esteghfar_9.mp3',
  './assets/audio/azkari/esteqaz_1.mp3',
  './assets/audio/azkari/esteqaz_2.mp3',
  './assets/audio/azkari/esteqaz_3.mp3',
  './assets/audio/azkari/esteqaz_4.mp3',
  './assets/audio/azkari/manzel_dukhool.mp3',
  './assets/audio/azkari/masaa_1.mp3',
  './assets/audio/azkari/masaa_4.mp3',
  './assets/audio/azkari/masaa_5.mp3',
  './assets/audio/azkari/mnzel_khurooj_1.mp3',
  './assets/audio/azkari/mnzel_khurooj_2.mp3',
  './assets/audio/azkari/rjoo3.mp3',
  './assets/audio/azkari/rokoob.mp3',
  './assets/audio/azkari/ruqya_1.mp3',
  './assets/audio/azkari/ruqya_10.mp3',
  './assets/audio/azkari/ruqya_11.mp3',
  './assets/audio/azkari/ruqya_12.mp3',
  './assets/audio/azkari/ruqya_13.mp3',
  './assets/audio/azkari/ruqya_14.mp3',
  './assets/audio/azkari/ruqya_15.mp3',
  './assets/audio/azkari/ruqya_16.mp3',
  './assets/audio/azkari/ruqya_17.mp3',
  './assets/audio/azkari/ruqya_2.mp3',
  './assets/audio/azkari/ruqya_3.mp3',
  './assets/audio/azkari/ruqya_4.mp3',
  './assets/audio/azkari/ruqya_5.mp3',
  './assets/audio/azkari/ruqya_6.mp3',
  './assets/audio/azkari/ruqya_7.mp3',
  './assets/audio/azkari/ruqya_8.mp3',
  './assets/audio/azkari/ruqya_9.mp3',
  './assets/audio/azkari/s_1.mp3',
  './assets/audio/azkari/s_10.mp3',
  './assets/audio/azkari/s_11.mp3',
  './assets/audio/azkari/s_12.mp3',
  './assets/audio/azkari/s_13.mp3',
  './assets/audio/azkari/s_14.mp3',
  './assets/audio/azkari/s_15.mp3',
  './assets/audio/azkari/s_16.mp3',
  './assets/audio/azkari/s_18.mp3',
  './assets/audio/azkari/s_2.mp3',
  './assets/audio/azkari/s_3.mp3',
  './assets/audio/azkari/s_4.mp3',
  './assets/audio/azkari/s_5.mp3',
  './assets/audio/azkari/s_6.mp3',
  './assets/audio/azkari/s_7.mp3',
  './assets/audio/azkari/s_8.mp3',
  './assets/audio/azkari/s_9.mp3',
  './assets/audio/azkari/safar.mp3',
  './assets/audio/azkari/salah_after_1.mp3',
  './assets/audio/azkari/salah_after_10.mp3',
  './assets/audio/azkari/salah_after_11.mp3',
  './assets/audio/azkari/salah_after_12.mp3',
  './assets/audio/azkari/salah_after_2.mp3',
  './assets/audio/azkari/salah_after_3.mp3',
  './assets/audio/azkari/salah_after_4.mp3',
  './assets/audio/azkari/salah_after_5.mp3',
  './assets/audio/azkari/salah_after_6.mp3',
  './assets/audio/azkari/salah_after_7.mp3',
  './assets/audio/azkari/salah_after_8.mp3',
  './assets/audio/azkari/salah_after_9.mp3',
  './assets/audio/azkari/salah_before_1.mp3',
  './assets/audio/azkari/salah_before_2.mp3',
  './assets/audio/azkari/salah_before_3.mp3',
  './assets/audio/azkari/salah_before_4.mp3',
  './assets/audio/azkari/salah_before_5.mp3',
  './assets/audio/azkari/salah_before_6.mp3',
  './assets/audio/azkari/salah_before_7.mp3',
  './assets/audio/azkari/slah_alal_mayt_part1.mp3',
  './assets/audio/azkari/slah_alal_mayt_part2.mp3',
  './assets/audio/azkari/slah_alal_mayt_part3.mp3',
  './assets/audio/azkari/slah_alal_mayt_part4.mp3',
  './assets/audio/azkari/sound_003_2_part.mp3',
  './assets/audio/azkari/sound_004_2_part.mp3',
  './assets/audio/azkari/sound_006_2_part.mp3',
  './assets/audio/azkari/sound_007_2_part.mp3',
  './assets/audio/azkari/sound_008_2_part.mp3',
  './assets/audio/azkari/sound_009_2_part.mp3',
  './assets/audio/azkari/sound_010_2_1_part.mp3',
  './assets/audio/azkari/sound_010_2_2_part.mp3',
  './assets/audio/azkari/sound_010_2_3_part.mp3',
  './assets/audio/azkari/sound_013_2_part.mp3',
  './assets/audio/azkari/sound_014_2_part.mp3',
  './assets/audio/azkari/sound_015_2_part.mp3',
  './assets/audio/azkari/sound_016_2_1_part.mp3',
  './assets/audio/azkari/sound_016_2_2_part.mp3',
  './assets/audio/azkari/sound_016_2_3_part.mp3',
  './assets/audio/azkari/sound_016_2_4_part.mp3',
  './assets/audio/azkari/sound_016_2_5_part.mp3',
  './assets/audio/azkari/sound_027_2_part.mp3',
  './assets/audio/azkari/sound_030_2_part.mp3',
  './assets/audio/azkari/sound_031_2_part.mp3',
  './assets/audio/azkari/sound_032_2_1_part.mp3',
  './assets/audio/azkari/sound_032_2_2_part.mp3',
  './assets/audio/azkari/sound_032_2_3_part.mp3',
  './assets/audio/azkari/sound_033_2_1_part.mp3',
  './assets/audio/azkari/sound_033_2_2_part.mp3',
  './assets/audio/azkari/sound_033_2_3_part.mp3',
  './assets/audio/azkari/sound_034_2_part.mp3',
  './assets/audio/azkari/sound_035_2_1_part.mp3',
  './assets/audio/azkari/sound_035_2_2_part.mp3',
  './assets/audio/azkari/sound_036_2_1_part.mp3',
  './assets/audio/azkari/sound_036_2_2_part.mp3',
  './assets/audio/azkari/sound_036_2_3_part.mp3',
  './assets/audio/azkari/sound_036_2_4_part.mp3',
  './assets/audio/azkari/sound_041_2_1_part.mp3',
  './assets/audio/azkari/sound_041_2_2_part.mp3',
  './assets/audio/azkari/sound_041_2_3_part.mp3',
  './assets/audio/azkari/sound_041_2_4_part.mp3',
  './assets/audio/azkari/sound_042_2_1_part.mp3',
  './assets/audio/azkari/sound_042_2_2_part.mp3',
  './assets/audio/azkari/sound_044_2_part.mp3',
  './assets/audio/azkari/sound_045_2_part.mp3',
  './assets/audio/azkari/sound_068_2_part.mp3',
  './assets/audio/azkari/sound_069_2_1_part.mp3',
  './assets/audio/azkari/sound_069_2_2_part.mp3',
  './assets/audio/azkari/sound_082_2_part.mp3',
  './assets/audio/azkari/sound_083_2_part.mp3',
  './assets/audio/azkari/sound_085_2_part.mp3',
  './assets/audio/azkari/sound_086_2_part.mp3',
  './assets/audio/azkari/sound_093_2_part.mp3',
  './assets/audio/azkari/sound_099_2_part.mp3',
  './assets/audio/azkari/sound_17_part.mp3',
  './assets/audio/azkari/sound_19_part.mp3',
  './assets/audio/azkari/sound_8_part.mp3',
  './assets/audio/azkari/wjaa_part.mp3',
  './assets/audio/azkari/zyart_alkboor_part.mp3'
];
const SURAH_AUDIO_CACHE = 'zad-quran-surah-audio-v461';
const APP_ASSETS = [
  './', './index.html', './offline.html', './privacy.html', './ui3-enhance.css', './ui3-enhance.js', './styles.css', './home-refresh.css', './ui2-polish.css', './config.js', './supabase-counter.js', './data.js', './app.js', './quran.js', './prayer.js', './enhancements.js', './quran-features.js', './quran-audio.js', './surah-audio.js', './quran-library.js', './audio-downloads.js', './quran-v48.js', './quran-video.js', './app-shell.js', './native-bridge.js', './simplification.js', './home-refresh.js',
  './azkari-import.js', './assets/css/fontawesome.min.css', './assets/css/local-fonts.css',
  './assets/webfonts/fa-solid-900.woff2', './assets/webfonts/fa-regular-400.woff2',
  './assets/fonts/amiri.ttf', './assets/fonts/tajawal-300.ttf', './assets/fonts/tajawal-500.ttf', './assets/fonts/tajawal-800.ttf',
  './manifest.webmanifest', './icons/icon.svg', './icons/icon-192.png', './icons/icon-512.png',
  './quran-data/chapters.json', './quran-data/uthmani.json', './quran-data/navigation.json', './quran-data/reciters.json', './quran-data/surah-reciters.json', './QURAN_DATA_LICENSE.txt', './THIRD_PARTY_ASSETS.txt'
];
APP_ASSETS.push(...AZKAR_AUDIO_ASSETS);

self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE_NAME).then(cache => cache.addAll(APP_ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(Promise.all([self.registration.navigationPreload?.enable(),caches.keys().then(keys => Promise.all(keys.filter(key => key !== CACHE_NAME && key !== AUDIO_CACHE && key !== SURAH_AUDIO_CACHE).map(key => caches.delete(key))))]).then(() => self.clients.claim()));
});
self.addEventListener('message', event => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
  if (event.data && event.data.type === 'GET_VERSION') event.source?.postMessage({type:'APP_VERSION',version:'4.9.3-beta.5.2'});
});
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  if (event.request.mode === 'navigate') {
    event.respondWith((event.preloadResponse||Promise.resolve()).then(preloaded=>preloaded||fetch(event.request)).then(response => {
      if (response.ok) caches.open(CACHE_NAME).then(cache => cache.put('./index.html', response.clone()));
      return response;
    }).catch(async () => (await caches.match('./index.html')) || caches.match('./offline.html')));
    return;
  }
  event.respondWith(caches.match(event.request).then(cached => {
    const network = fetch(event.request).then(response => {
      if (response.ok && new URL(event.request.url).origin === self.location.origin) caches.open(CACHE_NAME).then(cache => cache.put(event.request, response.clone()));
      return response;
    });
    if (cached) {
      network.catch(() => {});
      return cached;
    }
    return network;
  }).catch(() => new Response('', {status: 504, statusText: 'Offline'})));
});
